# Generated by Django 3.2.5 on 2022-03-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imginput',
            name='name',
            field=models.CharField(default='Some String', max_length=25),
        ),
    ]
