# Generated by Django 3.2.5 on 2022-03-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_imginput_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imginput',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
