# Generated by Django 3.2.5 on 2022-03-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_imginput_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imginput',
            name='name',
        ),
    ]
