# Generated by Django 3.2.5 on 2022-03-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_imginput_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imginput',
            name='date',
        ),
    ]
