# Generated by Django 3.2.5 on 2022-03-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_imginput_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imginput',
        ),
    ]
