# Generated by Django 3.2.5 on 2022-03-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_imginput'),
    ]

    operations = [
        migrations.CreateModel(
            name='pestimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimg', models.ImageField(upload_to='tempimgs/')),
            ],
        ),
    ]
